export const routes = {
  home: "/",
  main: "/main",
  orders: "/orders",
  contact: "/contact",
  register: "/register",
  login: "/login",
  addNewProduct: "/newProduct",
  newBurger: "/burgers",
  newTortilla: "/tortillas",
  newAddons: "/addons",
  newBeverages: "/beverages",
  admin: "/admin",
  user: "/user",
  checkOutmyOrder: "/checkOutmyOrder",
  addresForm: "/addresForm",
  editProduct: "/editProduct",
  editProductForm: "/editProductForm/:collection/:id",
};
