export const actionTypes = {
  FETCH_ALL_MEALS: "FETCH_ALL_MEALS",
  FETCH_ALL_ADDONS: "FETCH_ALL_ADDONS",
  FETCH_ALL_BEVERAGES: "FETCH_ALL_BEVERAGES",
  FETCH_ALL_SAUCES: "FETCH_ALL_SAUCES",
  ADD_MEAL: "ADD_MEAL",
  ADD_ADDON: "ADD_ADDON",
  ADD_BEVERAGES: "ADD_BEVERAGES",
  ADD_SAUCE: "ADD_SAUCE",
  UPDATE_MEAL: "UPDATE_MEAL",
  UPDATE_ADDON: "UPDATE_ADDON",
  UPDATE_SAUCE: "UPDATE_SAUCE",
  UPDATE_BEVERAGE: "UPDATE_UPDATE_BEVERAGE",

  GET_PRODUCT: "GET_PRODUCT",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  Order_Meal: "Order_Meal",
};
