export const actionTypes = {
  FETCH_ALL_MEALS: "FETCH_ALL_MEALS",
  FETCH_ALL_ADDONS: "FETCH_ALL_ADDONS",
  FETCH_ALL_BEVERAGES: "FETCH_ALL_BEVERAGES",
  FETCH_ALL_SAUCES: "FETCH_ALL_SAUCES",
  ADD_ITEM: "ADD_ITEM",
  ADD_ITEM_ERROR: "ADD_ITEM_ERROR",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  Order_Meal: "Order_Meal",
};
