export const actionTypes = {
  ADD_ITEM: "ADD_ITEM",
  ADD_ITEM_ERROR: "ADD_ITEM_ERROR",
  REMOVE_ITEM: "REMOVE_ITEM",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
};
